### ISSUE TITLE
Newest Version 1.0 Not Compatible with Older Mods or Dependencies 

### ISSUE THREAD

**Issue by HawkOverHK** [devyndamonster/OtherLoader#10]
Just recently came back to H3 and when I updated OtherLoader to Ver 1.0 on r2modman none of the mods would load as an error would pop into the console saying that Melon Mags depends on OtherLoader Ver 0.2.0 and that the dependency is not installed. This has only started to happen 3 days after OtherLoader has been updated to Ver 1.0 not sure if this is an issue from other mods not being updated or something. I will note that I am on Windows 11 but that should not be the issue with mod loading. 
![image](https://user-images.githubusercontent.com/91816186/135739551-cc25a35a-2535-4b08-85ae-1150b7edc639.png)

**Comment by RavenLunaris** [comment]
I have the same problem here.

**Comment by RavenLunaris** [comment]
except I still run Win10 and the issue breaks ALL mod loading, not just OtherLoader dependent mods.

**Comment by AtlasC0R3** [comment]
It seems that installing [Deliter](https://h3vr.thunderstore.io/package/Stratum/Deliter/) and [Mason](https://h3vr.thunderstore.io/package/Stratum/Mason/) fixes the issue.

**Comment by HawkOverHK** [comment]
interesting I guess I'll test that out as well.
