### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Kevin15673** [devyndamonster/OtherLoader#12]
I'm getting the following error while my game is loading, I'm new to h3vr modding and am using r2modman

[Error  :OtherLoader] Failed to load mod (C:\Users\Kevin\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\Default\BepInEx\plugins\devyndamonster-OtherLoader\resources\ : otherloader_assets)
[Error  :OtherLoader] System.MissingFieldException: Field 'FistVR.FVRObject.IsModContent' not found.
  at OtherLoader.ItemLoader+<ApplyLoadedAssetBundleAsync>d__12.MoveNext () [0x00000] in <filename unknown>:0
  at Stratum.Extensions.ExtIEnumerator.<TryCatch>g__MoveNext|5_0[Exception] (Stratum.Extensions.<>c__DisplayClass5_0`1& ) [0x00000] in <filename unknown>:0

[LogOutput.log](https://github.com/devyndamonster/OtherLoader/files/7573884/LogOutput.log)

**Comment by devyndamonster** [comment]
This is because version 1.1.2 and onward are targeting the Alpha branch of H3VR. You should either use the Alpha branch, or downgrade to version 1.1.1 and wait until the alpha hits main branch (should be a week from now)
