### ISSUE TITLE
Otherloader 1.2.0 - Secondaries and Tutorial Blocks won't load

### ISSUE THREAD

**Issue by NuigoFtrdrk** [devyndamonster/OtherLoader#13]
Hope this report helps

Secondaries on select custom weapons will not load, while others do.

My sample set is the NEXT Visions collection. Among the 16 weapons of the collection, which all load in the original Item Spawner, only a few weapons have their secondaries available.

- M107 and XM500 NGS has its magazine secondary

- Scout NGS has its magazine secondary

- Bren NGS has both its secondaries, making the max secondary amount a total of 2

The M107, Scout, and XM500 have their IDs and ISIDs filled out completely, however, the Bren's ID has the magazine related assets unfilled. This makes it confusing as it seems the issue is unrelated to IDs and ISIDs?

[I hope you give the sample set a shot as it contains various weapons with assets filled and unfilled with mixed results.](https://h3vr.thunderstore.io/package/Sora101Ven/NEXT_Visions_Series_Modpack/)

By extension, I wanted to ask if Tutorial Block support was added or not? This is less on hard data and could be an issue on my part, but my tests come out with the "Tutorial Soon!" message remaining. I would only hope for a response but again, iffy on what it could be, could be me or the loader.

The attachment provided is my sample Tutorial Block listing to help debunk what it could be, if support is available.

![tutblock](https://user-images.githubusercontent.com/77812891/147377207-4d507640-a040-4fbb-ab4f-fb117166d392.png)

Appreciate your hard work Devyn!

**Comment by devyndamonster** [comment]
Closing this issue because support for tutorial blocks is implemented in 1.3.0
