### ISSUE TITLE
Wrong version number in OtherLoader.cs

### ISSUE THREAD

**Issue by evenmorestupiderhats** [devyndamonster/OtherLoader#15]
In the source for v1.3.5 in Scripts/OtherLoader.cs, line 21 lists otherloaders version as 1.3.4

`[BepInPlugin("h3vr.otherloader", "OtherLoader", "1.3.4")]`

Packages that have a dependency of 1.3.5 or greater fail to load because of this.

**Comment by devyndamonster** [comment]
Closing, has been fixed
