### ISSUE TITLE
Infographics Don't Support Secondaries

### ISSUE THREAD

**Issue by ethanwa79** [devyndamonster/OtherLoader#2]
Adding an ItemspawnerControlInfographic to a ItemspawnerID marked as a secondary will cause the infographic to be overridden by its parent ItemspawnerID.
Reproduction: Add an itemspawnerControlInfographic to an ItemspawnerID. Make that ItemspawnerID a secondary of another object. The original ItemspawnerID will not display its infographic, and will instead display the infographic of its parent object (including if the field is empty)

**Comment by devyndamonster** [comment]
Fixed in 0.2.0 update, closing this issue
