### ISSUE TITLE
Odd FPS and GPU Utilization Issues

### ISSUE THREAD

**Issue by ChaoS-0515** [devyndamonster/OtherLoader#3]
Everything Works Just Fine With Any Mods Except For OtherLoader. When This Is Installed I Have Almost No GPU Usage Compared To My 60-85 Percent Usage Normally, And AT MOST 4 FPS. No One Else Seems To Have This Issue So Idk What The Problem Is.

**Comment by devyndamonster** [comment]
Wow that is bizarre. Could you run your game with otherloader installed, and then afterwards send your Bepinex Log output.log file?

**Comment by ChaoS-0515** [comment]
[LogOutput.log](https://github.com/devyndamonster/OtherLoader/files/6483345/LogOutput.log)

Here Ya Go

**Comment by ChaoS-0515** [comment]
Man Up And Died On Me

**Comment by devyndamonster** [comment]
Sorry, busy with college work, and can't investigate this right now. Ill be able to help with this in a couple days

**Comment by ChaoS-0515** [comment]
Oh Alright. Sorry I Didn't Know You Were Doing College Stuff. Good Luck!

**Comment by devyndamonster** [comment]
Alright, so when you ran with just Otherloader installed, and now other guns being loaded, it still lagged for you? I'm not seeing anything odd in the log file, so if you're having lag with no guns installed that's super weird

**Comment by ChaoS-0515** [comment]
i had everything uninstalled for a while to play the game but i just kinda threw all the mods in to get a log file.

and yeah it's really weird.

**Comment by devyndamonster** [comment]
What headset are you using? Also, what are your system specs?

**Comment by devyndamonster** [comment]
Closing this issue because it's old and I assume you got it figured out
